version: "3.8"
services:
  backend:
    build: .
    container_name: backend-app
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/docker
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    container_name: backend-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
