version: "3.8"
services:
  gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI_FILE=/run/secrets/user-mongo-uri
    secrets:
      - user-mongo-uri
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:6
    volumes:
      - user_data:/data/db
    ports:
      - "27018:27017"

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI_FILE=/run/secrets/product-mongo-uri
    secrets:
      - product-mongo-uri
    depends_on:
      - product-mongo

  product-mongo:
    image: mongo:6
    volumes:
      - product_data:/data/db
    ports:
      - "27019:27017"

secrets:
  user-mongo-uri:
    file: ./secrets/user-mongo-uri.txt
  product-mongo-uri:
    file: ./secrets/product-mongo-uri.txt

volumes:
  user_data:
  product_data:
