version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "5000:5000"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://user-mongo:27017/users
      - REDIS_URI=redis://redis:6379
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - user-mongo
      - redis
      - rabbitmq

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://product-mongo:27017/products
      - RABBITMQ_URI=amqp://rabbitmq:5672
    depends_on:
      - product-mongo
      - rabbitmq

  user-mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - user_mongo_data:/data/db

  product-mongo:
    image: mongo:6
    ports:
      - "27019:27017"
    volumes:
      - product_mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # apps
      - "15672:15672" # UI

volumes:
  user_mongo_data:
  product_mongo_data:
