version: "3.8"
services:
  gateway:
    build: ./gateway-service
    ports:
      - "4000:4000"
    depends_on:
      - user-service
      - product-service

  user-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://user-mongo:27017/users
    depends_on:
      - user-mongo

  user-mongo:
    image: mongo:6
    volumes:
      - user_data:/data/db
    ports:
      - "27018:27017"

  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://product-mongo:27017/products
    depends_on:
      - product-mongo

  product-mongo:
    image: mongo:6
    volumes:
      - product_data:/data/db
    ports:
      - "27019:27017"

volumes:
  user_data:
  product_data:
